/* eslint-disable  func-names */
/* eslint-disable max-len */
/* eslint quote-props: ['error', 'consistent'] */
// TODO: Replace this data with your own.
module.exports = {
  'RECIPE_EN_GB': {
    'line up': 'The line up includes Skeleton Gong, Bonnacons of Doom, Red Sun, Da Captain Trips, Electric Moon, The Cult of Dom Keller, Here and Now, Da Captain Trips, and more. To find out more about the bands you can ask me things like, tell me about Da Captain Trips. What would you like to do next?',
    'playing': 'The line up includes Skeleton Gong, Bonnacons of Doom, Red Sun, Da Captain Trips, Electric Moon, The Cult of Dom Keller, Here and Now, Da Captain Trips, and more. To find out more about the bands you can ask me things like, tell me about Da Captain Trips. What would you like to do next?',
    'skeleton gong': 'Skeleton Gong are Rick McCann, Rab Urqhart, Stewart McCosh, Old Man Gong, and Iain Carson-Brown. Skeleton Gong are known for their mix of heavy sludge/doom with clean psychedelic intervals, a love for 70\'s rock, loud guitars, pounding drums, analogue synths and of course gongs. They utilise a theatrical live show, relentless riffs and textured layers of synth and guitar, wrapped in melancholic melodies. What would you like to do now?',
    'bonnacons of doom': 'Whether congregating in dimly lit halls or in forests, and whether mediated by e-mailed audiofiles or infiltrating darker realms of consciousness, mysterious forces are being channelled by a shifting collective intent on psychic communion by any means necessary.Bonnacons of Doom’s identities may be shrouded and hidden in the live arena, yet the force of their vibrations - as captured on the unearthly vibrations and unholy revelations of their self-titled Rocket Recordings debut - is gloriously manifest. What would you like to do next?',
    'red sun': 'Red Sun are Mirco on Bass, Fede on drums and synth,and Eno on guitar. Red Sun formed in March 2014 after few long night jams under the starry sky of Albone, tiny village in the province of Piacenza (Italy), and open the first DesertFoxFest the following May. The trio composed by Stefano "Eno" on guitar, Mirco on bass (both former Silent River and The Big Red Sun) and Federico "Fredo" - former El Infernal Quinlan, now Cubedivision on drums and synth - serves a mix of psychedelia, space and hard and stoner instrumental rock. Would you like to hear about another act?',
    'electric moon': 'Electric Moon are Komet Lulu on Bass, Sula Bassana on Guitar. Electric Moon were founded in late 2009 by Komet Lulu (bass, vocals & lyrics) and Sula Bassana (guitar, fx organ, mix) together with the great drummer Pablo Carneval. In autumn 2013, Marcus called us because he had heard Electric Moon were searching for a drummer. This was some weeks before the Italy tour 2013 started and he joined as temporary drummer for this tour. After the tour, Electric Moon decided to involve Marcus in the band as constant drummer. Over the last 5 years, Electric Moon played many gigs, festivals and toured around through europe to spread their acidrocksound.',
    'the cult of dom keller': 'The Cult of Dom Keller are Ryan on vox and guitar, Neil on vox and keys, Jason on Guitar and synth, Liam on Bass, and Al on drums. They describe themselves as the sounds between the sounds in your head. BORN in 2007 Electric Moon are dark, psychedelic sonic alchemists from UK.',
    'here and now': 'Current members of Here and Now are Keith Da Bass - Missile Bass and Vocals, Mark Robson - Keyboards and Vocals, Andy Burrows - Guitars and Vocals, Gem Quinn - Drums and vocals. Here and Now grew out of a loosely formed jamming group known as Here-Now formed to play at the 1974 Windsor Free Festival. Named as such due to the floating membership policy and the influence of Ram Das\'s book Be Here Now',
    'da captain trips': 'Da Captain Trips are an Italian band who are much loved when they play <phoneme alphabet="ipa" ph="koʒfest">Kozfest</phoneme>. Band members are Kavitos on Guitar, Peppo on Bass, Tommy on drums and Bachis on synths. The band was formed as a joke in two thousand and nine by three overweight beardy friends. Cavitos on guitar, Sappah on drums and Peppo on bass. They started to jam and only the hunger could stop them. They shared the same passion for the space instrumental music based on infinite jam sessions, mostly influenced by all the psychedelic rock from the sixties and seventies.',
  },
};
